# Generated by Django 5.0.3 on 2024-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonsamochodowyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcars',
            name='carAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listcars',
            name='carImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
